// Code generated by MockGen. DO NOT EDIT.
// Source: src/models/users.go

// Package mock_models is a generated GoMock package.
package mock_models

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/singgihdwindaru/LetsVote/APIs/Auth.Api/src/models"
)

// MockIUserMysqlRepository is a mock of IUserMysqlRepository interface.
type MockIUserMysqlRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIUserMysqlRepositoryMockRecorder
}

// MockIUserMysqlRepositoryMockRecorder is the mock recorder for MockIUserMysqlRepository.
type MockIUserMysqlRepositoryMockRecorder struct {
	mock *MockIUserMysqlRepository
}

// NewMockIUserMysqlRepository creates a new mock instance.
func NewMockIUserMysqlRepository(ctrl *gomock.Controller) *MockIUserMysqlRepository {
	mock := &MockIUserMysqlRepository{ctrl: ctrl}
	mock.recorder = &MockIUserMysqlRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserMysqlRepository) EXPECT() *MockIUserMysqlRepositoryMockRecorder {
	return m.recorder
}

// GetUserByNIK mocks base method.
func (m *MockIUserMysqlRepository) GetUserByNIK(ctx context.Context, nik int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByNIK", ctx, nik)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByNIK indicates an expected call of GetUserByNIK.
func (mr *MockIUserMysqlRepositoryMockRecorder) GetUserByNIK(ctx, nik interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByNIK", reflect.TypeOf((*MockIUserMysqlRepository)(nil).GetUserByNIK), ctx, nik)
}

// InsertUser mocks base method.
func (m *MockIUserMysqlRepository) InsertUser(ctx context.Context, guid, metadata, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUser", ctx, guid, metadata, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertUser indicates an expected call of InsertUser.
func (mr *MockIUserMysqlRepositoryMockRecorder) InsertUser(ctx, guid, metadata, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUser", reflect.TypeOf((*MockIUserMysqlRepository)(nil).InsertUser), ctx, guid, metadata, hash)
}

// MockIUserUsecase is a mock of IUserUsecase interface.
type MockIUserUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIUserUsecaseMockRecorder
}

// MockIUserUsecaseMockRecorder is the mock recorder for MockIUserUsecase.
type MockIUserUsecaseMockRecorder struct {
	mock *MockIUserUsecase
}

// NewMockIUserUsecase creates a new mock instance.
func NewMockIUserUsecase(ctrl *gomock.Controller) *MockIUserUsecase {
	mock := &MockIUserUsecase{ctrl: ctrl}
	mock.recorder = &MockIUserUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserUsecase) EXPECT() *MockIUserUsecaseMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockIUserUsecase) CreateUser(ctx context.Context, request models.CreateUserRequest) (*models.CreateUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, request)
	ret0, _ := ret[0].(*models.CreateUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockIUserUsecaseMockRecorder) CreateUser(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIUserUsecase)(nil).CreateUser), ctx, request)
}

// CreateVoter mocks base method.
func (m *MockIUserUsecase) CreateVoter(ctx context.Context, request models.CreateVoterRequest) (*models.CreateVoterRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVoter", ctx, request)
	ret0, _ := ret[0].(*models.CreateVoterRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVoter indicates an expected call of CreateVoter.
func (mr *MockIUserUsecaseMockRecorder) CreateVoter(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVoter", reflect.TypeOf((*MockIUserUsecase)(nil).CreateVoter), ctx, request)
}

// SignIn mocks base method.
func (m *MockIUserUsecase) SignIn(ctx context.Context, request models.SignInRequest) (*models.SignInResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignIn", ctx, request)
	ret0, _ := ret[0].(*models.SignInResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignIn indicates an expected call of SignIn.
func (mr *MockIUserUsecaseMockRecorder) SignIn(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignIn", reflect.TypeOf((*MockIUserUsecase)(nil).SignIn), ctx, request)
}
